name: Checks and Tests

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Check
        run: yarn check

      - name: Lint
        run: yarn lint

  tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: yarn build

      - name: Build vxrn
        run: cd packages/vxrn && yarn build

      # @zetavg: `yarn build:web` run by `packages/one/test/setup.ts` seems to not
      # writing the output to `tests/test/dist` as expected even though it exits with 0
      # and have a normal output. IDK why. So running it here also as a workaround.
      # See: https://discord.com/channels/909986013848412191/1293586892201132143/1296556971113185382
      - name: Build test app
        run: |
          cd tests/test
          yarn build:web

      - name: Test
        run: yarn test

  notify:
    needs: [checks, tests]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify Discord on failure
        run: |
          echo "Checks or tests failed, sending message to Discord..."
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "content": "🚨 Checks or tests failed for commit `${{ github.sha }}` in [${{ github.repository }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}).\nSee the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

